### ISSUE TITLE
Put back all games that were previously there

### ISSUE THREAD

**Issue by RetriDoti** [bfirsh/jsnes-web#174]
All of the classic games I would play daily are gone! What happened?

**Comment by bfirsh** [comment]
https://www.ign.com/articles/2018/11/13/nintendo-rom-site-lawsuit-results-in-12-million-judgement

Sorry. :(

**Comment by bfirsh** [comment]
If you search google for "NES roms" you'll find them. Drag and drop the file onto the page to play it. :)
