### ISSUE TITLE
Can't Install via Yarn

### ISSUE THREAD

**Issue by nbarkhina** [bfirsh/jsnes-web#235]
When I do yarn install i'm getting the following errors - 

yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/react-router/-/react-router-4.4.0.tgz: Request
failed \"404 Not Found\"".

Please let me know if there's something i'm missing.

Thanks

**Comment by radio0but** [comment]
I have the same problem

**Comment by radio0but** [comment]
I found a solution if you have the same probleme as me your package.json file is not up to date. you just have to open it and find this line  `"react-router-dom": "^5.1.2",`  if its 4.x.x juste have to change this line and it should work.

**Comment by JobsLeeCN** [comment]
> I found a solution if you have the same probleme as me your package.json file is not up to date. you just have to open it and find this line ;
> `"react-router-dom": "^5.1.2", `
> 
> if its 4.x.x juste have to change this line and it should work.

That's right. Thank you! Maybe the version of the package should be UPDATED.
