### ISSUE TITLE
2 player controls don't work on keyboards without numpads

### ISSUE THREAD

**Issue by bfirsh** [bfirsh/jsnes-web#65]
Thanks Linkandar Airimder for the report, via email:

> I discovered that the controls for 2-player mode are unplayable to someone on a laptop without a number pad. If you would be so kind, would you be willing to change the controls to something similar to the 1st players? Nearly any control scheme would be preferable to the current.

**Comment by hibyguy** [comment]
Hey! @bfirsh I'd love to work on this as my first bug. Do you mind if i try to make a pull request for this? and do you have an suggestions?

**Comment by hibyguy** [comment]
I was thinking of adding an alternate button just next to the P2 control layout

**Comment by bfirsh** [comment]
Yeah please!

I’m not sure what the best solution is to be honest. The downside of being right next to each other is that isn’t actually practical to play. (Imagine two people actually trying to do that.)

**Comment by hibyguy** [comment]
I think for those comforable enough i think it can be done 😂
https://youtu.be/H_I9b6nBGAM

**Comment by hibyguy** [comment]
@bfirsh Oh, I didn't know if your comment was trying to on this but after review of some other flash games it pretty popular to have p1 do wasd and p2 arrows keys(and so on)

**Comment by bfirsh** [comment]
Yes, that seems reasonable, but it also needs to be done in a backwards compatible way.

Perhaps we could make P2 wasd, then add some P1 controls A/B/Start/Select controls near the arrow keys. Hmmmm. That seems overly complex.

**Comment by hibyguy** [comment]
Personally I like the left to right idea for control but its your thing, currently its assigned to p1 wasd p2 arrow keys; with p1 having G & H for A & B and p2 having ; & ' for A & B

**Comment by studywithyou** [comment]
Project finished

**Comment by studywithyou** [comment]
Touch  will working fine
Sound on ios safari 
Now trying to add gamepad controler 
Also wifi gamepad controller

**Comment by studywithyou** [comment]
Also thinking why not to try multi Online players 
Two playes through server of webrtc scripting of html5

**Comment by studywithyou** [comment]
Old project adding touch directly on buttons 
On canvas
Directly on canvas buttons 
Or make any button touch sensor

**Comment by hibyguy** [comment]
I'm confused, are you referring to something else you're working on, or my work here? @studywithyou

**Comment by studywithyou** [comment]
Who I am 
Lalit gangwani 

http://ol.pe.hu

Old project

**Comment by studywithyou** [comment]
Nes emulator for MOBILe web browser

**Comment by studywithyou** [comment]
@Ben Firshman

**Comment by bfirsh** [comment]
Fixed by #136.
